version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  test:
    jobs:
      - cypress/run:
          build: npm run build
          wait-on: http://localhost:5000
          start: npm start
